### ISSUE TITLE
Replace all does not replace currently "found" word

### ISSUE THREAD

**Issue by martajd** [jagthedrummer/codemirror-ui#13]
To reproduce:
1. Enter the same word multiple times 
2. Use the find box to find the word, and click it again until you are on the second instance of that word
3. Enter something into replace and check replace all
4. Execute. 
5. Notice that it has only replaced instances of the word after the word on which the cursor lies. 

It's a simple fix (once you root through the code base to see how it works!) 

EDIT: Crap, well my fix introduced a new bug so I'm going to sort it out here and submit a pull request once I've finished.

**Comment by jagthedrummer** [comment]
This should be fixed in version 0.0.17.

Thanks,
Jeremy
