### ISSUE TITLE
Tabbed Editor

### ISSUE THREAD

**Issue by mbarkhau** [jagthedrummer/codemirror-ui#2]
I know, I know, major feature request.

**Comment by jagthedrummer** [comment]
Yeah, that's a much larger feature than I currently plan to include with codemirror-ui.  I'm intending this to be a simple project to implement a single editor interface, with no additional requirements than codemirror itself.  

I have a general tabbed panel library that I have used together with codemirror-ui to build a tabbed editor type interface.  Here's the tab library.  

https://github.com/jagthedrummer/fancy-tabs

Please give it a look and see if it will help you out.

Thanks,
Jeremy
