### ISSUE TITLE
Demo page is down

### ISSUE THREAD

**Issue by cben** [jagthedrummer/codemirror-ui#24]
http://www.octolabs.com/javascripts/codemirror-ui/index.html is 404
I couldn't find your gh pages repo behind it (private I guess?). 

(Meanwhile I just forked with gh-pages branch so I can see the demo => http://cben.github.io/codemirror-ui/
Yes I see this project is old and semi-abandoned, last updated for codemirror v2; but a demo is useful to help people figure out if they'd want to bring it up to v3/v4...)

**Comment by jagthedrummer** [comment]
Thanks for the notice.  I'll get a new demo page put up and fix the link.  Good thought to slap one up with gh-pages.

**Comment by jagthedrummer** [comment]
Thanks for the info, @cben.  I just updated the README to point to the new demo page.  http://jagthedrummer.github.io/codemirror-ui/
