### ISSUE TITLE
Too much recursion when using onChange

### ISSUE THREAD

**Issue by notabeatle** [jagthedrummer/codemirror-ui#7]
When I set the onChange option for the related Codemirror instance, I get a 'too much recursion' error from Codemirror UI.  Specifically, I am trying to use it to enable a "save" button by calling a jQuery method when the onChange event gets fired, like so:

```
onChange: function(cminstance) { $('.cmsubmit').removeAttr('disabled'); }
```

I think I've fixed the problem by changing the "if" around line 50 of codemirror-ui.js (the line on which it errored) to read:

```
if (mirrorOptions.onChange) {
    mirrorOptions.oldOnChange = mirrorOptions.onChange;
    mirrorOptions.onChange = function() {
        mirrorOptions.oldOnChange();
        onChange();
}
```

Not thoroughly tested, but seems to work without breaking anything.  onChange behavior works as expected and, I believe, as intended by the original code on those lines, which was:

```
if (mirrorOptions.onChange) {
    mirrorOptions.onChange = function() {
        mirrorOptions.onChange();
        onChange();
}
```

**Comment by kipwilliams** [comment]
I have had the same issue.  This patch does fix the problem and it should be integrated into the main line

**Comment by jagthedrummer** [comment]
This should be fixed now.  Thanks for the info, and sorry for the huuuuuge delay.

https://github.com/jagthedrummer/codemirror-ui/commit/3bb142840ba5ddd8fc37677392fd4cc2c817edd3
