### ISSUE TITLE
Feature Request: Code folding

### ISSUE THREAD

**Issue by hades200082** [jagthedrummer/codemirror-ui#9]
All modern code editors have the ability to collapse blocks of code using +/- icons in the gutter.

Could this be done in CodeMirror UI?

I use CM for HTML/CSS (LESS)  editing and the ability to collapse whole nested blocks of LESS CSS down while I work on other areas would be amazing.

**Comment by jagthedrummer** [comment]
I think this is probably more suited as a feature request to CodeMirror than to CodeMirror-UI.  CodeMirror itself handles all of the actual code, gutter, and line number rendering.  CodeMirror-UI just adds the row of icons at the top.  Or maybe it needs to be a CodeMirror plugin by itself.  I think it would be very closely related to the formatting logic in terms of identifying collapsible blocks of code in any given language.
